- project:
    check:
      jobs:
        - f33-gcc:
            provides: CzechLight-deps-f33-gcc
            vars: &common_vars
              prepare_git_submodules: true
              artifacts:
                name: tarball
                glob: '*.tar.zst'
            post-run: &common_post_run
              - ci/post.yaml
            roles: &common_roles
              - zuul: return-built-artifact
            required-projects: &projects
              - github/CESNET/libyang
              - github/sysrepo/sysrepo
              - github/CESNET/libnetconf2
              - github/CESNET/Netopeer2
              - github/onqtam/doctest
              - github/docopt/docopt.cpp
              - github/rollbear/trompeloeil
              - github/tplgy/cppcodec
              - github/AmokHuginnsson/replxx
              - github/Kistler-Group/sdbus-cpp
            timeout: 1800

        - f33-clang-asan-ubsan:
            provides: CzechLight-deps-f33-clang-asan-ubsan
            vars: *common_vars
            required-projects: *projects
            post-run: *common_post_run
            roles: *common_roles
            timeout: 1800

        - f33-clang-tsan:
            provides: CzechLight-deps-f33-clang-tsan
            vars: *common_vars
            required-projects: *projects
            post-run: *common_post_run
            roles: *common_roles
            timeout: 2700

    promote:
      jobs:
        - promote-artifacts
