- project:
    check:
      jobs:
        - f31-gcc:
            provides: CzechLight-deps-f31-gcc
            vars: &common_vars
              prepare_git_submodules: true
              artifacts:
                name: tarball
                glob: '*.tar.xz'
            post-run: &common_post_run
              - ci/post.yaml
            roles: &common_roles
              - zuul: return-built-artifact
            required-projects: &projects
              - github/CESNET/libyang
              - github/sysrepo/libredblack
              - github/sysrepo/sysrepo
              - github/CESNET/libnetconf2
              - github/CESNET/Netopeer2
              - github/onqtam/doctest
              - github/docopt/docopt.cpp
              - github/gabime/spdlog
              - github/rollbear/trompeloeil
              - github/tplgy/cppcodec
              - github/AmokHuginnsson/replxx
              - github/pybind/pybind11
            timeout: 1800
