- job:
    name: deps-f40-gcc
    parent: f40-gcc
    pre-run: &common_pre_run
      - ci/pre.yaml
    provides: CzechLight-deps-f40-gcc
    vars: &common_vars
      prepare_git_submodules: true
      artifacts:
        name: tarball
        glob: '*.tar.zst'
    post-run: &common_post_run
      - ci/post.yaml
    roles: &common_roles
      - zuul: return-built-artifact
    required-projects: &projects
      - github/CESNET/libyang
      - CzechLight/libyang-cpp
      - github/sysrepo/sysrepo
      - CzechLight/sysrepo-cpp
      - github/CESNET/libnetconf2
      - CzechLight/libnetconf2-cpp
      - github/CESNET/Netopeer2
      - github/onqtam/doctest
      - github/rollbear/trompeloeil
      - github/AmokHuginnsson/replxx
      - github/Kistler-Group/sdbus-cpp
    timeout: 1800

- job:
    name: deps-f40-clang-asan-ubsan
    parent: f40-clang-asan-ubsan
    provides: CzechLight-deps-f40-clang-asan-ubsan
    vars: *common_vars
    required-projects: *projects
    pre-run: *common_pre_run
    post-run: *common_post_run
    roles: *common_roles
    timeout: 1800

- job:
    name: deps-f40-clang-tsan
    parent: f40-clang-tsan
    provides: CzechLight-deps-f40-clang-tsan
    vars: *common_vars
    required-projects: *projects
    pre-run: *common_pre_run
    post-run: *common_post_run
    roles: *common_roles
    timeout: 2700

- project:
    check:
      jobs:
        - deps-f40-gcc
        - deps-f40-clang-asan-ubsan
        - deps-f40-clang-tsan
        - netconf-cli-f40-clang-asan-ubsan:
            required-projects:
              - CzechLight/netconf-cli
            dependencies:
              - deps-f40-clang-asan-ubsan
            voting: false
        - velia-f40-clang-asan-ubsan:
            required-projects:
              - CzechLight/sysrepo-ietf-alarms
              - CzechLight/velia
            dependencies:
              - deps-f40-clang-asan-ubsan
            voting: false
        - rousette-f40-clang-asan-ubsan:
            required-projects:
              - CzechLight/rousette
            dependencies:
              - deps-f40-clang-asan-ubsan
            voting: false
        - sysrepo-ietf-alarms-f40-clang-asan-ubsan:
            required-projects:
              - CzechLight/sysrepo-ietf-alarms
            dependencies:
              - deps-f40-clang-asan-ubsan
            voting: false
        - cla-sysrepo-f40-clang-asan-ubsan:
            required-projects:
              - CzechLight/cla-sysrepo
            dependencies:
              - deps-f40-clang-asan-ubsan
            voting: false
        - czechlight-clearfog:
            required-projects:
              - CzechLight/br2-external
            requires: CzechLight-br2-build-clearfog
            voting: false

    promote:
      jobs:
        - promote-artifacts
