- project:
    check:
      jobs:
        - f29-gcc:
            provides: CzechLight-deps-f29-gcc
            vars: &common_vars
              prepare_git_submodules: true
              artifacts:
                name: tarball
                glob: '*.tar.xz'
            post-run: &common_post_run
              - ci/post.yaml
            roles: &common_roles
              - zuul: return-built-artifact
            required-projects: &projects
              - github/CESNET/libyang
              - github/sysrepo/libredblack
              - github/sysrepo/sysrepo
              - github/CESNET/libnetconf2
              - github/CESNET/Netopeer2
              - github/onqtam/doctest
              - github/docopt/docopt.cpp
              - github/gabime/spdlog
              - github/rollbear/trompeloeil
              - github/AmokHuginnsson/replxx
            timeout: 1800

        - f29-clang-asan:
            provides: CzechLight-deps-f29-clang-asan
            vars: *common_vars
            required-projects: *projects
            post-run: *common_post_run
            roles: *common_roles
            timeout: 1800
