- hosts: all
  tasks:
    - name: install pcre2
      package:
        name: pcre2-devel
        state: present
      become: true

    - name: install c_rehash
      package:
        name: openssl-perl
        state: present
      become: true

    - name: install PAM
      package:
        name: pam-devel
        state: present
      become: true

    - name: disable SSSD
      package:
        name: sssd-client
        state: absent
      become: true

    - name: check ulimit
      shell: |
        set -ex
        ulimit -a
        cat /etc/security/limits.conf
        ulimit -c unlimited
        ulimit -a
