- hosts: all
  tasks:
    - name: install pcre2
      package:
        name: pcre2-devel
        state: present
      become: true

    - name: install c_rehash
      package:
        name: openssl-perl
        state: present
      become: true

    - name: install PAM
      package:
        name: pam-devel
        state: present
      become: true

    - name: disable SSSD
      package:
        name: sssd-client
        state: absent
      become: true
